<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [
  <!ELEMENT aeropuertos (aeropuerto*)>
  <!ELEMENT aeropuerto (nombre, cerrado)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT cerrado (#PCDATA)>
]>
<aeropuertos>
  <aeropuerto>
    <nombre>Berlin Schönefeld (SFX)</nombre>
    <cerrado>no</cerrado>
  </aeropuerto>
  <aeropuerto>
    <nombre>Berlin Tempelhof (THF)</nombre>
    <cerrado>sí</cerrado>
  </aeropuerto>
</aeropuertos>
<!-- Se agregó el contenido esperado en <aeropuertos> y <aeropuerto> -->
