<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
  <!ELEMENT contabilidad (apunte*)>
  <!ELEMENT apunte (fecha, cantidad, concepto)>
  <!ELEMENT fecha (#PCDATA)>
  <!ELEMENT cantidad (#PCDATA)>
  <!ELEMENT concepto (#PCDATA)>
]>
<contabilidad>
  <apunte>
    <fecha>24 de febrero de 2011</fecha>
    <cantidad>1800,00 €</cantidad>
    <concepto>Salario</concepto>
  </apunte>
  <apunte>
    <fecha>28 de febrero de 2011</fecha>
    <cantidad>74,25 €</cantidad>
    <concepto>Recibo luz</concepto>
  </apunte>
</contabilidad>
<!-- Se incluyó el elemento <apunte> y sus campos, que no estaban definidos -->
